var os = require("os")

console.log("platform "+os.platform())
console.log("\nrelease "+os.release())
console.log("\nUptime  "+os.uptime())
console.log("\nhostname "+os.hostname())
console.log("\nhomedir "+os.homedir())
console.log("\narch "+os.arch())
console.log("\nfreemem"+os.freemem())
console.log("\ngetPriority "+os.getPriority())
console.log("\nloadavg "+os.loadavg())
console.log("\nendianness"+os.endianness())
console.log("\nrelease"+os.release())
console.log("\ntmpdir"+os.tmpdir())
console.log("\ntype"+os.type())
console.log("\nuserInfo "+os.userInfo())
console.log("\nnetworkInterfaces "+os.networkInterfaces())
// console.log("\nversion"+os.version())
// console.log("\nmachine "+os.machine())